### ISSUE TITLE
another project status

### ISSUE THREAD

**Issue by lzhhzl** [3c1u/S25Viewer#3]
Hello 3c1u, sorry to bother you. I followed your github project "nkts" for Nukitashi before, because I was wondering to make a port running on psvita, but I haven't follow it for a while. Until today, I noticed that the nkts project seems to have been deleted, I wonder if this project has been totally deleted and give up? Or is it being remade to a new project? Thank you for your work on nkts before.
And sorry I am not good at Japanese, so I have to use English.

**Comment by 3c1u** [comment]
> I wonder if this project has been totally deleted and give up?

I just lost interest in building it (which is pretty much incomplete; mostly due to the lacking of reverse-engineering skills). I simply gave it up.
